version: "3.9"

services:
  frontend:
    image: nginx:latest
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/html:/usr/share/nginx/html

  backend:
    image: php:fpm
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: db_name
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: db_name
    volumes:
      - ./mysql-data:/var/lib/mysql
